-- MySQL Script generated by MySQL Workbench
-- Sat Aug 11 22:46:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema web_customer_tracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web_customer_tracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web_customer_tracker` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema assetmanagementdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assetmanagementdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assetmanagementdb` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema spring_security_demo_bcrypt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spring_security_demo_bcrypt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spring_security_demo_bcrypt` DEFAULT CHARACTER SET latin1 ;
USE `web_customer_tracker` ;

-- -----------------------------------------------------
-- Table `web_customer_tracker`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_customer_tracker`.`customer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;

USE `assetmanagementdb` ;

-- -----------------------------------------------------
-- Table `assetmanagementdb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetmanagementdb`.`employee` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Username` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Enabled` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assetmanagementdb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetmanagementdb`.`role` (
  `Role_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Role_Description` VARCHAR(50) NULL DEFAULT NULL,
  `employee_ID` INT(11) NOT NULL,
  INDEX `fk_role_employee_idx` (`employee_ID` ASC),
  CONSTRAINT `fk_role_employee`
    FOREIGN KEY (`employee_ID`)
    REFERENCES `assetmanagementdb`.`employee` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `assetmanagementdb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetmanagementdb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assetmanagementdb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetmanagementdb`.`employee` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Username` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Enabled` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assetmanagementdb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assetmanagementdb`.`Role` (
  `RoleId` INT NOT NULL AUTO_INCREMENT,
  `RoleDescription` VARCHAR(45) NULL,
  `employee_ID` INT NOT NULL,
  PRIMARY KEY (`RoleId`),
  INDEX `fk_Role_employee1_idx` (`employee_ID` ASC),
  CONSTRAINT `fk_Role_employee1`
    FOREIGN KEY (`employee_ID`)
    REFERENCES `assetmanagementdb`.`employee` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `spring_security_demo_bcrypt` ;

-- -----------------------------------------------------
-- Table `spring_security_demo_bcrypt`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_security_demo_bcrypt`.`users` (
  `username` VARCHAR(50) NOT NULL,
  `password` CHAR(68) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `spring_security_demo_bcrypt`.`authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spring_security_demo_bcrypt`.`authorities` (
  `username` VARCHAR(50) NOT NULL,
  `authority` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `authorities_idx_1` (`username` ASC, `authority` ASC),
  CONSTRAINT `authorities_ibfk_1`
    FOREIGN KEY (`username`)
    REFERENCES `spring_security_demo_bcrypt`.`users` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
